version: '3.3'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./db-data:/var/lib/postgresql/data/pgdata
        ports:
            - 57019:5432
